### PR TITLE
Bif implementation

### PR DESCRIPTION
**Pull request by RyanSiu1995**
Hi @archSeer ,
I have implemented some simple functions.
I realized that there is a compilation problem in value.rs.
So I push the work along with the bug fix for this pull request first.

### CODE REVIEW

**Comment by RyanSiu1995** [comment]
I have got this error.
```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> src/value.rs:23:9
   |
19 | mod tuple;
   | ---------- not an extern crate passed with `--extern`
...
23 | pub use tuple::Tuple;
```
My compiler version is rustc 1.31.1 (b6c32da9b 2018-12-18)

**Comment by archseer** [comment]
Can you upgrade to 1.32? It was released recently and addresses this I think.

**Comment by RyanSiu1995** [comment]
I think we need to support 1.31 because you mentioned the minimum requirement for rustc is 1.31 in README.md.
Or we can update the README.md for solving this problem.

**Comment by archseer** [comment]
Great work!  🎊 🎊 🎊 We wrapped up maps :) I'll open some github issues later tonight!

**Pull request merged**
