### PR TITLE
Add unit tests for bif

### PR DESCRIPTION
**Pull request by RyanSiu1995**
Hello @archSeer ,
I am pretty new to rust language. I am still studying the code base. So I have commited some simple unit tests as an exercise first.
I think I try to implement some of the bif in the upcoming future!
Please kindly have some guidance or comment to me :)
Cheers!

### CODE REVIEW

**Comment by archSeer** [comment]
Hi, thanks for being the first contributor! 🎉  Code looks fine, but I noticed that the last commit just fixes the merge from the previous commit. Could you rebase 7d9f816 and b62cd2d together?

**Comment by archSeer** [comment]
In terms of easy bifs to get started on, `erlang:tuple_size/1` would be an easy one :) Just need to `if let Value::Tuple` to see if we have a tuple, then follow the embedded pointer and return the `len` attribute as a Value::Integer.

After that, maybe some of the map ones? I'd make a new file inside `src/bif/map.rs`, then you need to include it in `bif.rs` (add `mod map` under `mod chrono`). The HAMT interface is based on hamt-rs: https://crates.io/crates/hamt-rs

The documentation is here: https://docs.rs/hamt-rs/0.3.0/hamt_rs/struct.HamtMap.html and it's very similar to rust's regular HashMap (https://doc.rust-lang.org/std/collections/struct.HashMap.html) -- you can insert/remove/loop over it with an iterator etc.

**Comment by RyanSiu1995** [comment]
Okay, thank you for the guidance <3 Will create a pull request when I am done.

**Comment by archSeer** [comment]
Merged!

**Pull request merged**
